plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 20

Layout/LineLength:
  Exclude:
    - "*.gemspec"

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Alias:
  EnforcedStyle: prefer_alias
